# Generated by Django 2.2.6 on 2019-10-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kittens', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Puppy',
            new_name='Kitten',
        ),
    ]
